export const INVENTORY_PRODUCT_CARD_SERVICE_IMPORT_JOB_STATUS = {
    PROCESSING_READY: 'READY TO PROCESS',
    PROCESSING: 'PROCESSING',
    PROCESSING_FILE: 'PROCESSING FILE',
    PROCESSING_FILE_COMPLETE: 'PROCESSING FILE COMPLETE',
    PROCESSING_UPDATE_JOB_COUNT: 'UPDATE JOB COUNT',
    PROCESSING_READY_FOR_REVIEW: 'READY FOR REVIEW',
    PROCESSING_ADDING_TO_INVENTORY: 'ADDING TO INVENTORY',
    PROCESSING_CANCELLED: 'PROCESSING CANCELLED',
    PROCESSING_COMPLETE: 'PROCESSING COMPLETE',
    PROCESSING_REJECTED: 'PROCESSING REJECTED',
    PROCESSING_FAILED: 'PROCESSING FAILED',

}

export const INVENTORY_PRODUCT_CARD_SERVICE_IMPORT_JOB_PROVIDER_TYPE_NAME = {
  ROCA: 'Roca Sorter',
  TCG_PLAYER: 'TCG Player',
  PHYZBATCH: 'PhyzBatch',
};

export const INVENTORY_PRODUCT_CARD_SERVICE_IMPORT_JOB_UPLOAD_FILE_BUCKET_PATH = {
  ROCA: '/import/job/card/roca/upload/',
  TCG_PLAYER: '/import/job/card/tcgplayer/upload/',
  PHYZBATCH: '/import/job/card/phyzbatch/upload/',
};

export const INVENTORY_PRODUCT_CARD_SERVICE_IMPORT_JOB_PROVIDER_CARD_CONDITION = {
  NEAR_MINT: 'NM',
  LIGHTLY_PLAYED: 'LP',
  MODERATELY_PLAYED: 'MP',
  HEAVILY_PLAYED: 'HP',
  DAMAGED: 'D',
};

export const INVENTORY_PRODUCT_CARD_SERVICE_IMPORT_JOB_PROVIDER_ROCA_DATA_KEYS = {
  CARD_TCG_PLAYER_ID: 'TCGplayer Id',
  CARD_CONDITION: 'Condition',
  CARD_PRINTING: 'Condition',
  CARD_QTY: 'Add to Quantity',
};

export const INVENTORY_PRODUCT_CARD_SERVICE_IMPORT_JOB_PROVIDER_PHYZBATCH_CARD_DATA_KEYS = {
  CARD_TCG_PLAYER_ID: 'TCGplayer Id',
  CARD_SET_NAME: 'Set Name',
  CARD_NAME: 'Product Name',
  CARD_NUMBER: 'Number',
  CARD_CONDITION: 'Condition',
  CARD_TCG_PLAYER_MARKET_PRICE: 'TCG Market Price',
  CARD_TCG_PLAYER_LOW_PRICE: 'TCG Low Price',
  CARD_QTY: 'Add to Quantity',
};

export const INVENTORY_PRODUCT_CARD_SERVICE_IMPORT_JOB_PROVIDER_TCGPLAYER_CARD_DATA_KEYS = {
  CARD_TCG_PLAYER_ID: 'TCGplayer Id',
  CARD_SET_NAME: 'Set Name',
  CARD_NAME: 'Product Name',
  CARD_NUMBER: 'Number',
  CARD_CONDITION: 'Condition',
  CARD_TCG_PLAYER_MARKET_PRICE: 'TCG Market Price',
  CARD_TCG_PLAYER_LOW_PRICE: 'TCG Low Price',
  CARD_QTY: 'Add to Quantity',
};

export const INVENTORY_PRODUCT_CARD_SERVICE_IMPORT_JOB_PROVIDER_CARD_PRINTING = {
  FOIL: 'Foil',
  NORMAL: 'Normal',
};


