export const INVENTORY_BATCH_LOAD_JOB_PRODUCT_CARD_STATUS = {
    PROCESSING: 'PROCESSING',
    PROCESSING_INVENTORY_CARDS: 'PROCESSING INVENTORY CARDS',
    PROCESSING_INVENTORY_CARDS_COMPLETE: 'PROCESSING INVENTORY CARDS COMPLETE',
    PROCESSING_INVENTORY_CARD_PRICES: 'PROCESSING INVENTORY CARD PRICES',
    PROCESSING_INVENTORY_CARD_PRICES_COMPLETE: 'PROCESSING INVENTORY CARD PRICES COMPLETE',
    PROCESSING_COMPLETE: 'PROCESSING COMPLETE',
    PROCESSING_FAILED: 'PROCESSING FAILED',

}