

export const BASE_PRICING = {
    BASE_PRICE_LEVEL: 'tcgplayer-low',
    MINIMUM_PRICE_ENABLED: true,
    MINIMUM_PRICE: 0.49,
    ROUNDING_PRICE_ENABLED: true
}

export const CONDITION_PRICING = {
    CONDITION_PRICE_PERCENTAGE_NM: 100,
    CONDITION_PRICE_PERCENTAGE_LP: 90,
    CONDITION_PRICE_PERCENTAGE_MP: 80,
    CONDITION_PRICE_PERCENTAGE_HP: 60,
    CONDITION_PRICE_PERCENTAGE_DM: 50
}
