export const INVENTORY_PRODUCT_CARD_SERVICE_CREATE_JOB_STATUS = {
    PROCESSING: 'PROCESSING',
    PROCESSING_INVENTORY_CARDS: 'PROCESSING INVENTORY CARDS',
    PROCESSING_INVENTORY_CARDS_COMPLETE: 'PROCESSING INVENTORY CARDS COMPLETE',
    PROCESSING_INVENTORY_CARD_PRICES: 'PROCESSING INVENTORY CARD PRICES',
    PROCESSING_INVENTORY_CARD_PRICES_COMPLETE: 'PROCESSING INVENTORY CARD PRICES COMPLETE',
    PROCESSING_READY_FOR_REVIEW: 'READY FOR REVIEW',
    PROCESSING_ADDING_TO_INVENTORY: 'ADDING TO INVENTORY',
    PROCESSING_CANCELLED: 'PROCESSING CANCELLED',
    PROCESSING_COMPLETE: 'PROCESSING COMPLETE',
    PROCESSING_REJECTED: 'PROCESSING REJECTED',
    PROCESSING_FAILED: 'PROCESSING FAILED',

}