export const INVENTORY_PRODUCT_CARD_SERVICE_UPDATE_PRICE_JOB_STATUS = {
    PROCESSING_READY: 'READY FOR PROCESSING',
    PROCESSING: 'PROCESSING',
    PROCESSING_COMPLETE: 'PROCESSING COMPLETE',
    PROCESSING_FAILED: 'PROCESSING FAILED',

}