export const PRICE_BATCH_UPDATE_JOB_PRODUCT_CARD_STATUS = {
    PROCESSING: 'PROCESSING',
    PROCESSING_CARD_PRICE_UPDATES: 'PROCESSING CARD PRICE UPDATES',
    PROCESSING_COMPLETE: 'PROCESSING COMPLETE',
    PROCESSING_FAILED: 'PROCESSING FAILED',
}