export interface InventoryProductCardServiceImportJobProviderTypeDataKey {
    inventoryProductCardServiceImportJobProviderTypeDataKeyTCGPlayerId: string;
    inventoryProductCardServiceImportJobProviderTypeDataKeyCondition: string;
    inventoryProductCardServiceImportJobProviderTypeDataKeyPrinting: string;
    inventoryProductCardServiceImportJobProviderTypeDataKeyQty: string;
}