export const BUYLIST_IMPORT_PRODUCT_CARD_PROVIDER_TYPE_CARD_CONDITION = {
  NEAR_MINT: 'NM',
  LIGHTLY_PLAYED: 'LP',
  MODERATELY_PLAYED: 'MP',
  HEAVILY_PLAYED: 'HP',
  DAMAGED: 'D',
};

export const BUYLIST_IMPORT_PRODUCT_CARD_PROVIDER_TYPE_CARD_PRINTING = {
  FOIL: 'Foil',
  NORMAL: 'Normal',
};


